@echo off
echo 🌐 Build et déploiement frontend avec correction lien contraintes...
cd frontend
echo 📦 Installation des dépendances...
npm install
echo 🏗️ Build du frontend...
npm run build
echo 📁 Copie vers dossier deploy...
xcopy /s /y build\* ..\deploy\www\
echo ✅ Frontend déployé avec correction !
cd ..
